// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBw_tx1pSuXhie0s3gqcR4OPP-IQASBUdA',
    appId: '1:593067165327:web:257db95fe3c580971d92fa',
    messagingSenderId: '593067165327',
    projectId: 'gradutionproject-2',
    authDomain: 'gradutionproject-2.firebaseapp.com',
    storageBucket: 'gradutionproject-2.firebasestorage.app',
    measurementId: 'G-QHZQW6QELG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAPlcblkwpg2N06lDfJJJgK_iFEbJ9hD5w',
    appId: '1:593067165327:android:812fe3726c202dc01d92fa',
    messagingSenderId: '593067165327',
    projectId: 'gradutionproject-2',
    storageBucket: 'gradutionproject-2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB7MZ_edLSE-tUq4Hz_JebqmeMqgqzFU4g',
    appId: '1:593067165327:ios:c561cc0c84bd0c191d92fa',
    messagingSenderId: '593067165327',
    projectId: 'gradutionproject-2',
    storageBucket: 'gradutionproject-2.firebasestorage.app',
    iosBundleId: 'com.example.project2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB7MZ_edLSE-tUq4Hz_JebqmeMqgqzFU4g',
    appId: '1:593067165327:ios:c561cc0c84bd0c191d92fa',
    messagingSenderId: '593067165327',
    projectId: 'gradutionproject-2',
    storageBucket: 'gradutionproject-2.firebasestorage.app',
    iosBundleId: 'com.example.project2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBw_tx1pSuXhie0s3gqcR4OPP-IQASBUdA',
    appId: '1:593067165327:web:11b8364bc1cc49231d92fa',
    messagingSenderId: '593067165327',
    projectId: 'gradutionproject-2',
    authDomain: 'gradutionproject-2.firebaseapp.com',
    storageBucket: 'gradutionproject-2.firebasestorage.app',
    measurementId: 'G-YP6DJ3EPVH',
  );
}
